/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */
import type { ApiNowPlayingStationMount } from './apiNowPlayingStationMount';

export interface ApiAdminRelay {
  /** The administrator password for the frontend (if applicable). */
  admin_pw?: string;
  /**
   * Station description
   * @nullable
   */
  description?: string | null;
  /**
   * The genre of the station
   * @nullable
   */
  genre?: string | null;
  /** Station ID */
  id?: number;
  mounts?: ApiNowPlayingStationMount[];
  /**
   * Station name
   * @nullable
   */
  name?: string | null;
  /**
   * The port used by this station to serve its broadcasts.
   * @nullable
   */
  port?: number | null;
  /** The relay password for the frontend (if applicable). */
  relay_pw?: string;
  /**
   * Station "short code", used for URL and folder paths
   * @nullable
   */
  shortcode?: string | null;
  /**
   * Which broadcasting software (frontend) the station uses
   * @nullable
   */
  type?: string | null;
  /**
   * Station homepage URL
   * @nullable
   */
  url?: string | null;
}
