/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */

export type ApiAdminStorageLocationAllOf = {
  /** The storage adapter to use for this location. */
  adapter?: string;
  /**
   * The optional Dropbox App Key.
   * @nullable
   */
  dropboxAppKey?: string | null;
  /**
   * The optional Dropbox App Secret.
   * @nullable
   */
  dropboxAppSecret?: string | null;
  /**
   * The optional Dropbox Auth Token.
   * @nullable
   */
  dropboxAuthToken?: string | null;
  id?: number;
  isFull?: boolean;
  /**
   * The local path, if the local adapter is used, or path prefix for S3/remote adapters.
   * @nullable
   */
  path?: string | null;
  /**
   * The S3 bucket name for S3 adapters.
   * @nullable
   */
  s3Bucket?: string | null;
  /**
   * The credential key for S3 adapters.
   * @nullable
   */
  s3CredentialKey?: string | null;
  /**
   * The credential secret for S3 adapters.
   * @nullable
   */
  s3CredentialSecret?: string | null;
  /**
   * The optional custom S3 endpoint S3 adapters.
   * @nullable
   */
  s3Endpoint?: string | null;
  /**
   * The region for S3 adapters.
   * @nullable
   */
  s3Region?: string | null;
  /**
   * The API version for S3 adapters.
   * @nullable
   */
  s3Version?: string | null;
  /**
   * The host for SFTP adapters
   * @nullable
   */
  sftpHost?: string | null;
  /**
   * The password for SFTP adapters
   * @nullable
   */
  sftpPassword?: string | null;
  /**
   * The port for SFTP adapters
   * @nullable
   */
  sftpPort?: number | null;
  /**
   * The private key for SFTP adapters
   * @nullable
   */
  sftpPrivateKey?: string | null;
  /**
   * The private key pass phrase for SFTP adapters
   * @nullable
   */
  sftpPrivateKeyPassPhrase?: string | null;
  /**
   * The username for SFTP adapters
   * @nullable
   */
  sftpUsername?: string | null;
  /**
   * The stations using this storage location, if any.
   * @nullable
   */
  stations?: string[] | null;
  /** @nullable */
  storageAvailable?: string | null;
  /** @nullable */
  storageAvailableBytes?: string | null;
  /** @nullable */
  storageQuota?: string | null;
  /** @nullable */
  storageQuotaBytes?: string | null;
  /** @nullable */
  storageUsed?: string | null;
  /** @nullable */
  storageUsedBytes?: string | null;
  /** @nullable */
  storageUsedPercent?: number | null;
  /** The type of storage location. */
  type?: string;
  /** The URI associated with the storage location. */
  uri?: string;
};
