/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */

export type ApiDetailedSongHistoryAllOf = {
  /** The sum total change of listeners between the song's start and ending. */
  delta_total?: number;
  /** Whether the entry is visible on public playlists. */
  is_visible?: boolean;
  /** Number of listeners when song playback ended. */
  listeners_end?: number;
  /** Number of listeners when the song playback started. */
  listeners_start?: number;
};
