/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */

export interface ApiError {
  /** The numeric code of the error. */
  code?: number;
  /** Stack traces and other supplemental data. */
  extra_data?: unknown[];
  /**
   * The HTML-formatted text description of the error.
   * @nullable
   */
  formatted_message?: string | null;
  /** The text description of the error. */
  message?: string;
  /** Used for API calls that expect an \Entity\Api\Status type response. */
  success?: boolean;
  /** The programmatic class of error. */
  type?: string;
}
