/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */

export interface ApiHasSongFields {
  /**
   * The song album.
   * @nullable
   */
  album?: string | null;
  /**
   * The song artist.
   * @nullable
   */
  artist?: string | null;
  /**
   * The song genre.
   * @nullable
   */
  genre?: string | null;
  /**
   * The International Standard Recording Code (ISRC) of the file.
   * @nullable
   */
  isrc?: string | null;
  /**
   * Lyrics to the song.
   * @nullable
   */
  lyrics?: string | null;
  /** The song title, usually "Artist - Title" */
  text?: string;
  /**
   * The song title.
   * @nullable
   */
  title?: string | null;
}
