/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */
import type { ApiListenerDevice } from './apiListenerDevice';
import type { ApiListenerLocation } from './apiListenerLocation';

export interface ApiListener {
  /** UNIX timestamp that the user first connected. */
  connected_on?: number;
  /** Number of seconds that the user has been connected. */
  connected_time?: number;
  /** UNIX timestamp that the user disconnected (or the latest timestamp if they are still connected). */
  connected_until?: number;
  device?: ApiListenerDevice;
  /** A unique identifier for this listener/user agent (used for unique calculations). */
  hash?: string;
  /** The listener's IP address */
  ip?: string;
  location?: ApiListenerLocation;
  /** Whether the user is connected to a local mount point or a remote one. */
  mount_is_local?: boolean;
  /** The display name of the mount point. */
  mount_name?: string;
  /** The listener's HTTP User-Agent */
  user_agent?: string;
}
