/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */

export interface ApiListenerDevice {
  /**
   * Summary of the listener browser family.
   * @nullable
   */
  browser_family?: string | null;
  /**
   * Summary of the listener client.
   * @nullable
   */
  client?: string | null;
  /** If the listener device is likely a crawler. */
  is_bot?: boolean;
  /** If the listener device is likely a browser. */
  is_browser?: boolean;
  /** If the listener device is likely a mobile device. */
  is_mobile?: boolean;
  /**
   * Summary of the listener OS family.
   * @nullable
   */
  os_family?: string | null;
}
