/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */

export interface ApiListenerLocation {
  /**
   * The approximate city of the listener.
   * @nullable
   */
  city?: string | null;
  /**
   * The approximate country of the listener.
   * @nullable
   */
  country?: string | null;
  /** A description of the location. */
  description?: string;
  /**
   * Latitude.
   * @nullable
   */
  lat?: number | null;
  /**
   * Latitude.
   * @nullable
   */
  lon?: number | null;
  /**
   * The approximate region/state of the listener.
   * @nullable
   */
  region?: string | null;
}
