/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */
import type { ApiNowPlayingCache } from './apiNowPlayingCache';
import type { ApiNowPlayingListeners } from './apiNowPlayingListeners';
import type { ApiNowPlayingLive } from './apiNowPlayingLive';
import type { ApiNowPlayingNowPlaying } from './apiNowPlayingNowPlaying';
import type { ApiNowPlayingPlayingNext } from './apiNowPlayingPlayingNext';
import type { ApiNowPlayingSongHistory } from './apiNowPlayingSongHistory';
import type { ApiNowPlayingStation } from './apiNowPlayingStation';

export interface ApiNowPlaying {
  /**
   * Debugging information about where the now playing data comes from.
   * @nullable
   */
  cache?: ApiNowPlayingCache;
  /** Whether the stream is currently online. */
  is_online?: boolean;
  listeners?: ApiNowPlayingListeners;
  live?: ApiNowPlayingLive;
  /** @nullable */
  now_playing?: ApiNowPlayingNowPlaying;
  /** @nullable */
  playing_next?: ApiNowPlayingPlayingNext;
  song_history?: ApiNowPlayingSongHistory[];
  station?: ApiNowPlayingStation;
}
