/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */
import type { ApiNowPlayingLiveArt } from './apiNowPlayingLiveArt';

export interface ApiNowPlayingLive {
  /**
   * URL to the streamer artwork (if available).
   * @nullable
   */
  art?: ApiNowPlayingLiveArt;
  /**
   * The start timestamp of the current broadcast, if one is available.
   * @nullable
   */
  broadcast_start?: number | null;
  /** Whether the stream is known to currently have a live DJ. */
  is_live?: boolean;
  /** The current active streamer/DJ, if one is available. */
  streamer_name?: string;
}
