/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */
import type { ApiSong } from './apiSong';

export interface ApiNowPlayingStationQueue {
  /** UNIX timestamp when the AutoDJ is expected to queue the song for playback. */
  cued_at?: number;
  /** Duration of the song in seconds */
  duration?: number;
  /** Indicates whether the song is a listener request. */
  is_request?: boolean;
  /** UNIX timestamp when playback is expected to start. */
  played_at?: number;
  /**
   * Indicates the playlist that the song was played from, if available, or empty string if not.
   * @nullable
   */
  playlist?: string | null;
  song?: ApiSong;
}
