/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */

/**
 * Debugging information about where the now playing data comes from.
 * @nullable
 */
export type ApiNowPlayingCache = typeof ApiNowPlayingCache[keyof typeof ApiNowPlayingCache] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApiNowPlayingCache = {
  hit: 'hit',
  database: 'database',
  station: 'station',
} as const;
