/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */

export type ApiNowPlayingStationMountAllOf = {
  /** If the mount is the default mount for the parent station */
  is_default?: boolean;
  /** The relative path that corresponds to this mount point */
  path?: string;
};
