/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */
import type { ApiNowPlayingStationHlsUrl } from './apiNowPlayingStationHlsUrl';
import type { ApiNowPlayingStationMount } from './apiNowPlayingStationMount';
import type { ApiNowPlayingStationRemote } from './apiNowPlayingStationRemote';

export interface ApiNowPlayingStation {
  /** Which AutoDJ software (backend) the station uses */
  backend?: string;
  /** Station description */
  description?: string;
  /** Which broadcasting software (frontend) the station uses */
  frontend?: string;
  /** If the station has HLS streaming enabled. */
  hls_enabled?: boolean;
  /** If the HLS stream should be the default one for the station. */
  hls_is_default?: boolean;
  /** HLS Listeners */
  hls_listeners?: number;
  /**
   * The full URL to listen to the HLS stream for the station.
   * @nullable
   */
  hls_url?: ApiNowPlayingStationHlsUrl;
  /** Station ID */
  id?: number;
  /** If the station is public (i.e. should be shown in listings of all stations) */
  is_public?: boolean;
  /** The full URL to listen to the default mount of the station */
  listen_url?: unknown;
  mounts?: ApiNowPlayingStationMount[];
  /** Station name */
  name?: string;
  /** The playlist download URL in M3U format. */
  playlist_m3u_url?: unknown;
  /** The playlist download URL in PLS format. */
  playlist_pls_url?: unknown;
  /** The public player URL for the station. */
  public_player_url?: unknown;
  remotes?: ApiNowPlayingStationRemote[];
  /** Station "short code", used for URL and folder paths */
  shortcode?: string;
  /** The station's IANA time zone */
  timezone?: string;
  /**
   * The public URL of the station.
   * @nullable
   */
  url?: string | null;
}
