/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */
import type { ApiSong } from './apiSong';

export interface ApiNowPlayingSongHistory {
  /** Duration of the song in seconds */
  duration?: number;
  /** Indicates whether the song is a listener request. */
  is_request?: boolean;
  /** UNIX timestamp when playback started. */
  played_at?: number;
  /**
   * Indicates the playlist that the song was played from, if available, or empty string if not.
   * @nullable
   */
  playlist?: string | null;
  /** Song history unique identifier */
  sh_id?: number;
  song?: ApiSong;
  /**
   * Indicates the current streamer that was connected, if available, or empty string if not.
   * @nullable
   */
  streamer?: string | null;
}
