/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */

export interface ApiPodcastMedia {
  /** @nullable */
  id?: string | null;
  length?: number;
  /** @nullable */
  length_text?: string | null;
  /** @nullable */
  original_name?: string | null;
  /** @nullable */
  path?: string | null;
}
