/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */
import type { ApiPodcastEpisodeAllOfMedia } from './apiPodcastEpisodeAllOfMedia';
import type { ApiPodcastEpisodeAllOfPlaylistMedia } from './apiPodcastEpisodeAllOfPlaylistMedia';

export type ApiPodcastEpisodeAllOf = {
  /** @nullable */
  art?: string | null;
  art_updated_at?: number;
  created_at?: number;
  description?: string;
  description_short?: string;
  /** @nullable */
  episode_number?: number | null;
  explicit?: boolean;
  has_custom_art?: boolean;
  has_media?: boolean;
  id?: string;
  is_published?: boolean;
  /** @nullable */
  link?: string | null;
  /** @nullable */
  media?: ApiPodcastEpisodeAllOfMedia;
  /** @nullable */
  playlist_media?: ApiPodcastEpisodeAllOfPlaylistMedia;
  /** @nullable */
  playlist_media_id?: string | null;
  publish_at?: number;
  /** @nullable */
  season_number?: number | null;
  title?: string;
};
