/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */
import type { ApiPodcastCategory } from './apiPodcastCategory';

export type ApiPodcastAllOf = {
  art?: string;
  art_updated_at?: number;
  author?: string;
  /** An array containing podcast-specific branding configuration */
  branding_config?: unknown[];
  categories?: ApiPodcastCategory[];
  description?: string;
  description_short?: string;
  email?: string;
  episodes?: number;
  has_custom_art?: boolean;
  id?: string;
  is_enabled?: boolean;
  is_published?: boolean;
  language?: string;
  language_name?: string;
  /** @nullable */
  link?: string | null;
  playlist_auto_publish?: boolean;
  /** @nullable */
  playlist_id?: number | null;
  source?: string;
  storage_location_id?: number;
  title?: string;
};
