/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */

export type ApiStationMediaAllOf = {
  /** URL to the album art. */
  art?: string;
  /** The latest time (UNIX timestamp) when album art was updated. */
  art_updated_at?: number;
  custom_fields?: string[];
  extra_metadata?: unknown[];
  /** The media's identifier. */
  id?: number;
  /** The song duration in seconds. */
  length?: number;
  /** The formatted song duration (in mm:ss format) */
  length_text?: string;
  /** The UNIX timestamp when the database was last modified. */
  mtime?: number;
  /** The relative path of the media file. */
  path?: string;
  playlists?: unknown[];
  /** The media file's 32-character unique song identifier hash */
  song_id?: string;
  /** A unique identifier associated with this record. */
  unique_id?: string;
  /** The UNIX timestamp when the item was first imported into the database. */
  uploaded_at?: number;
};
