/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */

export interface ApiStationPlaylistQueue {
  /** The song artist. */
  artist?: string;
  /** ID of the StationPlaylistMedia record associating this track with the playlist */
  media_id?: number;
  /** The song's 32-character unique identifier hash */
  song_id?: string;
  /**
   * ID of the StationPlaylistMedia record associating this track with the playlist
   * @nullable
   */
  spm_id?: number | null;
  /** The song title. */
  title?: string;
}
