/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */
import type { ApiSong } from './apiSong';

export interface ApiStationOnDemand {
  /** URL to download/play track. */
  download_url?: string;
  media?: ApiSong;
  playlist?: string;
  /** Track ID unique identifier */
  track_id?: string;
}
