/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */
import type { ApiStationScheduleType } from './apiStationScheduleType';

export interface ApiStationSchedule {
  /** The full name of the type and name combined. */
  description?: string;
  /** The start time of the schedule entry, in ISO 8601 format. */
  end?: string;
  /** The end time of the schedule entry, in UNIX format. */
  end_timestamp?: number;
  /** Unique identifier for this schedule entry. */
  id?: number;
  /** Whether the event is currently ongoing. */
  is_now?: boolean;
  /** Either the playlist or streamer's display name. */
  name?: string;
  /** The start time of the schedule entry, in ISO 8601 format. */
  start?: string;
  /** The start time of the schedule entry, in UNIX format. */
  start_timestamp?: number;
  /** The name of the event. */
  title?: string;
  /** The type of this schedule entry. */
  type?: ApiStationScheduleType;
}
