/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */

export type ApiStationRemoteAllOf = {
  /** @nullable */
  admin_password?: string | null;
  /** @nullable */
  autodj_bitrate?: number | null;
  /** @nullable */
  autodj_format?: string | null;
  /** @nullable */
  custom_listen_url?: string | null;
  /** @nullable */
  display_name?: string | null;
  enable_autodj?: boolean;
  /** @nullable */
  id?: number | null;
  is_editable?: boolean;
  is_public?: boolean;
  is_visible_on_public_pages?: boolean;
  /** The most recent number of total (non-unique) listeners. */
  listeners_total?: number;
  /** The most recent number of unique listeners. */
  listeners_unique?: number;
  /** @nullable */
  mount?: string | null;
  /** @nullable */
  source_mount?: string | null;
  /** @nullable */
  source_password?: string | null;
  /** @nullable */
  source_port?: number | null;
  /** @nullable */
  source_username?: string | null;
  type?: string;
  url?: string;
};
