/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */

/**
 * The type of this schedule entry.
 */
export type ApiStationScheduleType = typeof ApiStationScheduleType[keyof typeof ApiStationScheduleType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApiStationScheduleType = {
  playlist: 'playlist',
  streamer: 'streamer',
} as const;
