/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */

export type FileTypes = typeof FileTypes[keyof typeof FileTypes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FileTypes = {
  directory: 'directory',
  media: 'media',
  cover_art: 'cover_art',
  unprocessable_file: 'unprocessable_file',
  other: 'other',
} as const;
