/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */

export type GetStationHistoryParams = {
/**
 * The start date for records, in PHP-supported date/time format. (https://www.php.net/manual/en/datetime.formats.php)
 */
start?: string;
/**
 * The end date for records, in PHP-supported date/time format. (https://www.php.net/manual/en/datetime.formats.php)
 */
end?: string;
};
