/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */

export type GetScheduleParams = {
/**
 * The date/time to compare schedule items to. Defaults to the current date and time.
 */
now?: string;
/**
 * The number of upcoming/ongoing schedule entries to return. Defaults to 5.
 */
rows?: number;
};
