/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */
import type { SettingsAnalytics } from './settingsAnalytics';
import type { SettingsIpSource } from './settingsIpSource';
import type { SettingsPublicTheme } from './settingsPublicTheme';

export interface Settings {
  /**
   * ACME (LetsEncrypt) domain name(s).
   * @nullable
   */
  acme_domains?: string | null;
  /**
   * ACME (LetsEncrypt) e-mail address.
   * @nullable
   */
  acme_email?: string | null;
  /** Always Use HTTPS */
  always_use_ssl?: boolean;
  /**
   * Listener Analytics Collection
   * @nullable
   */
  analytics?: SettingsAnalytics;
  /**
   * API 'Access-Control-Allow-Origin' header
   * @nullable
   */
  api_access_control?: string | null;
  app_unique_identifier?: string;
  /**
   * The default avatar URL.
   * @nullable
   */
  avatar_default_url?: string | null;
  /**
   * The external avatar service to use when fetching avatars.
   * @nullable
   */
  avatar_service?: string | null;
  /** Whether backup is enabled. */
  backup_enabled?: boolean;
  /** Whether to exclude media in automated backups. */
  backup_exclude_media?: boolean;
  /**
   * The output format for the automated backup.
   * @nullable
   */
  backup_format?: string | null;
  /** Number of backups to keep, or infinite if zero/null. */
  backup_keep_copies?: number;
  /**
   * The output of the latest automated backup task.
   * @nullable
   */
  backup_last_output?: string | null;
  /** The UNIX timestamp when automated backup was last run. */
  backup_last_run?: number;
  /**
   * The storage location ID for automated backups.
   * @nullable
   */
  backup_storage_location?: number | null;
  /**
   * The timecode (i.e. 400 for 4:00AM) when automated backups should run.
   * @nullable
   */
  backup_time_code?: string | null;
  /**
   * Site Base URL
   * @nullable
   */
  base_url?: string | null;
  /** Check for Updates and Announcements */
  check_for_updates?: boolean;
  /**
   * Default Album Art URL
   * @nullable
   */
  default_album_art_url?: string | null;
  /** Whether to enable 'advanced' functionality in the system that is intended for power users. */
  enable_advanced_features?: boolean;
  /** Whether to use high-performance static JSON for Now Playing data updates. */
  enable_static_nowplaying?: boolean;
  /**
   * This installation's external IP.
   * @nullable
   */
  external_ip?: string | null;
  /** The UNIX timestamp when the Maxmind Geolite was last downloaded. */
  geolite_last_run?: number;
  /**
   * The license key for the Maxmind Geolite download.
   * @nullable
   */
  geolite_license_key?: string | null;
  /** Hide Album Art on Public Pages */
  hide_album_art?: boolean;
  /** Hide AzuraCast Branding on Public Pages */
  hide_product_name?: boolean;
  /** Days of Playback History to Keep */
  history_keep_days?: number;
  /**
   * Homepage Redirect URL
   * @nullable
   */
  homepage_redirect_url?: string | null;
  /**
   * AzuraCast Instance Name
   * @nullable
   */
  instance_name?: string | null;
  /**
   * Custom CSS for Internal Pages
   * @nullable
   */
  internal_custom_css?: string | null;
  /**
   * IP Address Source
   * @nullable
   */
  ip_source?: SettingsIpSource;
  /**
   * An API key to connect to Last.fm services, if provided.
   * @nullable
   */
  last_fm_api_key?: string | null;
  /** Enable e-mail delivery across the application. */
  mail_enabled?: boolean;
  /**
   * The e-mail address of the sender of system e-mails.
   * @nullable
   */
  mail_sender_email?: string | null;
  /**
   * The name of the sender of system e-mails.
   * @nullable
   */
  mail_sender_name?: string | null;
  /**
   * The host to send outbound SMTP mail.
   * @nullable
   */
  mail_smtp_host?: string | null;
  /**
   * The password when connecting to SMTP mail.
   * @nullable
   */
  mail_smtp_password?: string | null;
  /** The port for sending outbound SMTP mail. */
  mail_smtp_port?: number;
  /** Whether to use a secure (TLS) connection when sending SMTP mail. */
  mail_smtp_secure?: boolean;
  /**
   * The username when connecting to SMTP mail.
   * @nullable
   */
  mail_smtp_username?: string | null;
  /** Prefer Browser URL (If Available) */
  prefer_browser_url?: boolean;
  /**
   * Custom CSS for Public Pages
   * @nullable
   */
  public_custom_css?: string | null;
  /**
   * Custom JS for Public Pages
   * @nullable
   */
  public_custom_js?: string | null;
  /**
   * Base Theme for Public Pages
   * @nullable
   */
  public_theme?: SettingsPublicTheme;
  /** The UNIX timestamp when setup was last completed. */
  setup_complete_time?: number;
  /** Temporarily disable all sync tasks. */
  sync_disabled?: boolean;
  /** The last run timestamp for the unified sync task. */
  sync_last_run?: number;
  /** The UNIX timestamp when updates were last checked. */
  update_last_run?: number;
  /**
   * Results of the latest update check.
   * @nullable
   */
  update_results?: unknown[] | null;
  /** Attempt to fetch album art from external sources in API requests. */
  use_external_album_art_in_apis?: boolean;
  /** Attempt to fetch album art from external sources when processing media. */
  use_external_album_art_when_processing_media?: boolean;
  /** Use Web Proxy for Radio */
  use_radio_proxy?: boolean;
}
