/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */
import type { StationMountAllOfAutodjFormat } from './stationMountAllOfAutodjFormat';

export type StationMountAllOf = {
  /** @nullable */
  authhash?: string | null;
  /** @nullable */
  autodj_bitrate?: number | null;
  /** @nullable */
  autodj_format?: StationMountAllOfAutodjFormat;
  /** @nullable */
  custom_listen_url?: string | null;
  /** @nullable */
  display_name?: string | null;
  enable_autodj?: boolean;
  /** @nullable */
  fallback_mount?: string | null;
  frontend_config?: unknown[];
  is_default?: boolean;
  is_public?: boolean;
  is_visible_on_public_pages?: boolean;
  /** The most recent number of total (non-unique) listeners. */
  listeners_total?: number;
  /** The most recent number of unique listeners. */
  listeners_unique?: number;
  max_listener_duration?: number;
  name?: string;
  /** @nullable */
  relay_url?: string | null;
};
