/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */
import type { StationPlaylistAllOfRemoteType } from './stationPlaylistAllOfRemoteType';

export type StationPlaylistAllOf = {
  avoid_duplicates?: boolean;
  /** @nullable */
  backend_options?: string | null;
  /** Whether this playlist's media is included in 'on demand' download/streaming if enabled. */
  include_in_on_demand?: boolean;
  include_in_requests?: boolean;
  is_enabled?: boolean;
  /** If yes, do not send jingle metadata to AutoDJ or trigger web hooks. */
  is_jingle?: boolean;
  name?: string;
  order?: unknown;
  play_per_hour_minute?: number;
  play_per_minutes?: number;
  play_per_songs?: number;
  /** Podcast> */
  podcasts?: unknown[];
  /** The total time (in seconds) that Liquidsoap should buffer remote URL streams. */
  remote_buffer?: number;
  /** @nullable */
  remote_type?: StationPlaylistAllOfRemoteType;
  /** @nullable */
  remote_url?: string | null;
  /** StationSchedule> */
  schedule_items?: unknown[];
  source?: unknown;
  type?: unknown;
  weight?: number;
};
