/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */

export type StationScheduleAllOf = {
  /**
   * Array of ISO-8601 days (1 for Monday, 7 for Sunday)
   * @nullable
   */
  days?: string | null;
  end_time?: number;
  loop_once?: boolean;
  start_time?: number;
};
