/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */

export type StationAllOf = {
  /** The number of 'last played' history items to show for a station in API responses. */
  api_history_items?: number;
  /** An array containing station-specific backend configuration */
  backend_config?: unknown[];
  /** The backend adapter (liquidsoap,etc) */
  backend_type?: unknown;
  /** An array containing station-specific branding configuration */
  branding_config?: unknown[];
  /** @nullable */
  description?: string | null;
  /** @nullable */
  disconnect_deactivate_streamer?: number | null;
  /** Whether HLS streaming is enabled. */
  enable_hls?: boolean;
  /** Whether this station has a public 'on-demand' streaming and download page. */
  enable_on_demand?: boolean;
  /** Whether the 'on-demand' page offers download capability. */
  enable_on_demand_download?: boolean;
  /** Whether this station is visible as a public page and in a now-playing API response. */
  enable_public_page?: boolean;
  /** Whether listeners can request songs to play on this station. */
  enable_requests?: boolean;
  /** Whether streamers are allowed to broadcast to this station at all. */
  enable_streamers?: boolean;
  /** An array containing station-specific frontend configuration */
  frontend_config?: unknown[];
  /** The frontend adapter (icecast,shoutcast,remote,etc) */
  frontend_type?: unknown;
  /** @nullable */
  genre?: string | null;
  /** If set to 'false', prevents the station from broadcasting but leaves it in the database. */
  is_enabled?: boolean;
  /** Whether a streamer is currently active on the station. */
  is_streamer_live?: boolean;
  /** The full display name of the station. */
  name?: string;
  /** @nullable */
  radio_base_dir?: string | null;
  /** @nullable */
  request_delay?: number | null;
  /** @nullable */
  request_threshold?: number | null;
  /** The URL-friendly name for the station, typically auto-generated from the full station name. */
  short_name?: string;
  /**
   * The time zone that station operations should take place in.
   * @nullable
   */
  timezone?: string | null;
  /** @nullable */
  url?: string | null;
};
