/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */

export type StationWebhookAllOf = {
  /** Detailed webhook configuration (if applicable) */
  config?: unknown[];
  is_enabled?: boolean;
  /** Internal details used by the webhook to preserve state. */
  metadata?: unknown[];
  /**
   * The nickname of the webhook connector.
   * @nullable
   */
  name?: string | null;
  /** List of events that should trigger the webhook notification. */
  triggers?: unknown[];
  /** The type of webhook connector to use. */
  type?: unknown;
};
