/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * AzuraCast
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 * OpenAPI spec version: 0.20.1
 */

export type UserAllOf = {
  created_at?: number;
  email?: string;
  /** @nullable */
  locale?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  new_password?: string | null;
  /** Role> */
  roles?: unknown[];
  /** @nullable */
  show_24_hour_time?: boolean | null;
  /** @nullable */
  two_factor_secret?: string | null;
  updated_at?: number;
};
